export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";

export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAILURE = "GET_CART_ITEMS_FAILURE";

export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const FILTER_TYPE = "FILTER_TYPE";

export const SORT_ASC_RATING = "SORT_ASC_RATING";

export const SORT_DESC_RATING = "SORT_DESC_RATING";

export const SORT_ASC_PRICE = "SORT_ASC_PRICE";

export const SORT_DESC_PRICE = "SORT_DESC_PRICE";

export const NEXT_PAGE = "NEXT_PAGE";

export const PREV_PAGE = "PREV_PAGE";

export const FILTER_SORT = "FILTER_SORT";

export const FILTER_PAGINATION = "FILTER_PAGINATION";
