
export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE="USER_LOGIN_FAILURE";



// export const UPDATE_BOOK_RECORD_REQUEST="UPDATE_BOOK_RECORD_REQUEST";
// export const UPDATE_BOOK_RECORD_SUCCESS="UPDATE_BOOK_RECORD_SUCCESS";
// export const UPDATE_BOOK_RECORD_FAILURE="UPDATE_BOOK_RECORD_FAILURE";