

 export const GET_HOTELS_REQUEST = "GET_HOTELS_REQUEST"
 export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS"
 export const GET_HOTELS_FAILURE = "GET_HOTELS_FAILURE"

 
export const UPDATE_HOTEL_RECORD_REQUEST="UPDATE_HOTEL_RECORD_REQUEST";
export const UPDATE_HOTEL_RECORD_SUCCESS="UPDATE_HOTEL_RECORD_SUCCESS";
export const UPDATE_HOTEL_RECORD_FAILURE="UPDATE_HOTEL_RECORD_FAILURE";