export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";


 export const GET_TODO_LISTS_REQUEST = "GET_TODO_LISTS_REQUEST"
 export const GET_TODO_LISTS_SUCCESS = "GET_TODO_LISTS_SUCCESS"
 export const GET_TODO_LISTS_FAILURE = "GET_TODO_LISTS_FAILURE"



 export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
 export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
 export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"; 

 export const TOGGLE_TODO_REQUEST = "TOGGLE_TODO_REQUEST";
 export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
 export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE"; 

 export const REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST";
 export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
 export const REMOVE_TODO_FAILURE = "REMOVE_TODO_FAILURE"; 


 export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
 export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
 export const EDIT_TODO_FAILURE = "EDIT_TODO_FAILURE"; 