// export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
// export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const ADD_COUNT = "ADD_COUNT";
export const SUBSTRACT_COUNT = "SUBSTRACT_COUNT";

export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";