

 export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST"
 export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
 export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE"

 

 export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
 export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
 export const ADD_STUDENT_FAILURE = "ADD_STUDENT_FAILURE";

 export const ADD_TEST_REQUEST = "ADD_TEST_REQUEST";
 export const ADD_TEST_SUCCESS = "ADD_TEST_SUCCESS";
 export const ADD_TEST_FAILURE = "ADD_TEST_FAILURE";
 
 export const GET_TESTS_REQUEST = "GET_TESTS_REQUEST";
 export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS";
 export const GET_TESTS_FAILURE = "GET_TESTS_FAILURE";

 export const ADD_TEACHER_REQUEST = "ADD_TEACHER_REQUEST";
 export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
 export const ADD_TEACHER_FAILURE = "ADD_TEACHER_FAILURE";
 
 export const GET_TEACHER_REQUEST = "GET_TEACHER_REQUEST";
 export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
 export const GET_TEACHER_FAILURE = "GET_TEACHER_FAILURE";
 

 
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const FILTER_TYPE = "FILTER_TYPE";

export const SORT_ASC_RATING = "SORT_ASC_RATING";

export const SORT_DESC_RATING = "SORT_DESC_RATING";

export const SORT_ASC_PRICE = "SORT_ASC_PRICE";

export const SORT_DESC_PRICE = "SORT_DESC_PRICE";

export const NEXT_PAGE = "NEXT_PAGE";

export const PREV_PAGE = "PREV_PAGE";

export const FILTER_SORT = "FILTER_SORT";

export const FILTER_PAGINATION = "FILTER_PAGINATION";
