
 export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST"
 export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"
 export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE"

 
export const UPDATE_BOOK_RECORD_REQUEST="UPDATE_BOOK_RECORD_REQUEST";
export const UPDATE_BOOK_RECORD_SUCCESS="UPDATE_BOOK_RECORD_SUCCESS";
export const UPDATE_BOOK_RECORD_FAILURE="UPDATE_BOOK_RECORD_FAILURE";